name: tests
on: 
  workflow_run:
    workflows:
      - "build"
    types:
      - "completed"
jobs: 
  windows: 
    runs-on: windows-2022
    steps: 
      - name: Test Run
        run: |
          echo "Testing Workflow"